language: go

go:
  - 1.12.x

os:
  - linux
  - windows

env:
  - GO111MODULE=on

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -v -race ./...

notifications:
  email: false
